# Generated by Django 4.2.9 on 2024-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='date_of_change_status',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Change Status'),
        ),
    ]
