# Generated by Django 4.2.9 on 2024-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reserve_date_of_change_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='min_days_to_rent',
        ),
        migrations.AddField(
            model_name='reserve',
            name='days_to_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='Days to Rent'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='end_rent_date',
            field=models.DateField(default=None, verbose_name='Start Rent Date'),
            preserve_default=False,
        ),
    ]
