# Generated by Django 4.2.9 on 2024-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpaymentinformation',
            name='company_percentage',
            field=models.FloatField(verbose_name='Company_Percentage'),
        ),
        migrations.AlterField(
            model_name='basicpaymentinformation',
            name='insurance_percentage',
            field=models.FloatField(verbose_name='Insurance_Percentage'),
        ),
        migrations.AlterField(
            model_name='basicpaymentinformation',
            name='value_added_percentage',
            field=models.FloatField(verbose_name='Value_Added_Percentage'),
        ),
    ]
