# Generated by Django 4.2.9 on 2024-02-02 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserve', '0002_reserve_date_of_change_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='Balance')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Card Number')),
                ('shaba_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shaba Number')),
                ('account_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Account Number')),
                ('update_account_information_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Account Information Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('paid_status', models.BooleanField(default=False, verbose_name='Paid_Status')),
                ('date_of_request', models.DateTimeField(verbose_name='Date_of_Request')),
                ('date_of_withdrawal', models.DateTimeField(blank=True, null=True, verbose_name='Date_of_Withdrawal')),
                ('tracking_payment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking Payment')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_price', models.PositiveBigIntegerField(verbose_name='Total_Price')),
                ('car_value', models.PositiveBigIntegerField(verbose_name='Car_Value')),
                ('company_percentage', models.PositiveIntegerField(verbose_name='Company_Percentage')),
                ('value_added_percentage', models.PositiveIntegerField(verbose_name='Value_Added_Percentage')),
                ('insurance_percentage', models.PositiveIntegerField(verbose_name='Insurance_Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.reserve', verbose_name='Reserve')),
            ],
        ),
    ]
